### PR TITLE
Fixed CI

### PR DESCRIPTION
**Pull request by foxycode**
It was little bit harder than I expected. I needed to add `strict_types` and return type hints. Not all checks could be fixed, I can't add return type hints where parent class don't have them for example. Hope it is ok this way.

### CODE REVIEW

**Comment by foxycode** [comment]
@enumag Is it ok this way?

**Comment by enumag** [comment]
Fine by me.

@VBoss WDYT? Anything else before we can make a new release?

**Comment by foxycode** [comment]
@enumag @VBoss  I see Symfony 4.* tests failed, but they are in allowed failures. Was it ok before or not?

**Comment by enumag** [comment]
@foxycode Other SF4 tests are passing. I'm guessing these are builds against dev symfony, which means 4.3 in this case. Since 4.3 will be released soon, I think we need to have this fixed.

**Comment by foxycode** [comment]
@enumag I don't know why it is failing and I believe it's not related to my changes. You can probably merge this.

**Comment by VBoss** [comment]
Failing tests are related to changes in events in symfony 4.3-dev, more here https://github.com/Kdyby/Events/pull/120#discussion_r271074516
There is some big BC break in arguments for events, I didnt looked into that closely but this should be fixed in another PR, because that BC break will probably persist to our Kdyby implementations too.

**Comment by VBoss** [comment]
Anyway PR is ok we can make release.

**Comment by enumag** [comment]
Ah so the BC break will be solved in Kdyby/Events and doesn't directly affect Kdyby/Console? In that case we can make the new release.

**Pull request merged**
