### PR TITLE
Optional dependencies

### PR DESCRIPTION
**Pull request by pepakriz**
I would like to use this extension without dependencies on `nette/application` and `nette/http` (CLI only app). Is this solution acceptable for you?

### CODE REVIEW

**Comment by JanTvrdik** [comment]
This probably closes https://github.com/Kdyby/Console/issues/30

**Comment by enumag** [comment]
I agree with @JanTvrdik but I've never really used these features. Other people might prefer backward compatibility.

**Comment by fprochazka** [comment]
There were two reasons for integrating it this way:
- simplicity
- ability to generate links in CLI

The second one is partially solved using the [LinkGenerator](https://api.nette.org/2.3.8/Nette.Application.LinkGenerator.html), which still generates wrong urls without faked http, but the application-presenter is not needed anymore. The first reason remains.

One solution which would benefit all comes in mind: extract new package with deadsimple integration of sf console into Nette and have this one to be the "stupid but simple" way of integrating it, which would extend it.

**Comment by fprochazka** [comment]
Either way, this PR is a good addition and I'll be happily merging it.

**Comment by fprochazka** [comment]
@pepakriz thank you!

**Pull request closed without merging**
