### PR TITLE
New Symfony version: Fixes E_DEPRECATED errors and failing test

### PR DESCRIPTION
**Pull request by MartinMystikJonas**
Fixes also #25

### CODE REVIEW

**Comment by fprochazka** [comment]
@MartinMystikJonas the tests have failed.

**Comment by MartinMystikJonas** [comment]
@fprochazka Sorry about that. I fixed errors in my code. There is still one failing test, but I do not see any connection to changes I made.

**Comment by MartinMystikJonas** [comment]
@fprochazka Looks like Symfony also changed formatting of usage output. Test fixed to use current formating is in second commit.

**Comment by fprochazka** [comment]
Thank you kind sir!

**Pull request merged**
