### PR TITLE
Application: fix Throwable handling

### PR DESCRIPTION
**Pull request by matej21**
it was probably broken by 2451e936432f402367ba4de40c99c3afab5ee4bd

### CODE REVIEW

**Comment by enumag** [comment]
I'm pretty sure I didn't break that - I only changed code inside the `} catch (\Exception $e) {` so I could't have changed the behavior for Throwable.

Anyway 👍

**Comment by matej21** [comment]
@enumag I think other throwable errors were logged here https://github.com/Kdyby/Console/commit/2451e936432f402367ba4de40c99c3afab5ee4bd#diff-c893c788a9128ec350af949ac5724960L191

**Comment by enumag** [comment]
Oh. Yeah that could have affected it. Nice catch. :-)

**Comment by fprochazka** [comment]
Thank you guys!

**Pull request closed without merging**
