### PR TITLE
nette 3.0 compatibility

### PR DESCRIPTION
**Pull request by MartkCz**
getConfig hasn't any parameters.

### CODE REVIEW

**Comment by enumag** [comment]
@MartkCz Does this work with Nette 2.4 as well?

**Comment by enumag** [comment]
ping @MartkCz

**Comment by MartkCz** [comment]
Yes, works. In current version, defaults parameters aren't combined with config values and config values aren't checked (source: https://api.nette.org/2.4/source-DI.CompilerExtension.php.html#55-81).

**Comment by enumag** [comment]
Merged, thanks.

**Pull request merged**
